version: "3.5"

services:
  postgres:
    container_name: postgres_container_1
    image: postgres
    environment:
      POSTGRES_DATABASE: shop
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: lebedi
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container1
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: den.lebedinsky@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "8080:80"
    networks:
      - postgres
    restart: unless-stopped

  redis:
    image: "bitnami/redis"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/bitnami/redis/data"

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  redis_data:
